// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkafsykwvoktrorayexm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrYWZzeWt3dm9rdHJvcmF5ZXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDUwNzAsImV4cCI6MjA2NDE4MTA3MH0.zmmwags9kn1Asiihy3B3LkdXUp0q6wSd6ATTzGBsd1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);